name: Selenium TestNG CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install Chrome
      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      # Step 3: Install ChromeDriver
      - name: Install ChromeDriver
        uses: nanasess/setup-chromedriver@v2

      # Step 4: Install dependencies
      - name: Install dependencies
        run: sudo apt-get install -y libnss3 libgbm1 libxss1 libasound2t64

      # Step 5: Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      
      # Step 7: Build and run TestNG tests
      - name: Build and run tests
        run: mvn clean test
